repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
