repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest
        stages: [commit]
        language: system
        pass_filenames: false
        always_run: true

      - id: isort
        name: isort
        entry: python -m isort
        stages: [commit]
        language: system
        types: [python]

      - id: black
        name: black
        entry: python -m black
        stages: [commit]
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: python -m flake8
        stages: [commit]
        language: system
        types: [python]
